import pandas as pd
import streamlit as st

st.title('Inflasi')

inflasi = {
    '2020': { 
        'Januari': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,
        }, 
        'Februari': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Maret': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'April': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Mei': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Juni': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Juli': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Agustus': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'September': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Oktober': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'November': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Desember': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,
        }
    },
    '2021': { 
        'Januari': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Februari': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Maret': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'April': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Mei': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Juni': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Juli': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Agustus': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'September': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Oktober': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'November': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Desember': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,
        }},
    '2022': { 
       'Januari': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Februari': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Maret': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'April': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Mei': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Juni': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Juli': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Agustus': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'September': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Oktober': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'November': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Desember': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,
        }},
    '2023': { 
        'Januari': {
            'Umum': 0.68,
            'Makanan, Minuman dan Tembakau': 2.31,
            'Pakaian dan Alas Kaki': 0.06,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': -0.07,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.05,
            'Kesehatan': 0.08,
            'Transportasi': -0.26,
            'Informasi, Komunikasi dan Jasa Keuangan': '-',
            'Rekreasi, Olahraga dan Budaya': '-',
            'Pendidikan': 0.84,
            'Penyediaan Makanan dan Minuman/Restoran': '-',
            'Perawatan Pribadi dan Jasa Lainnya': 0.43,

        }, 
        'Februari': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Maret': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'April': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Mei': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Juni': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Juli': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Agustus': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'September': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Oktober': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'November': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Desember': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,
        }},
    '2024': { 
        'Januari': {
            'Umum': 0.68,
            'Makanan, Minuman dan Tembakau': 2.31,
            'Pakaian dan Alas Kaki': 0.06,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': -0.07,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.05,
            'Kesehatan': 0.08,
            'Transportasi': -0.26,
            'Informasi, Komunikasi dan Jasa Keuangan': '-',
            'Rekreasi, Olahraga dan Budaya': '-',
            'Pendidikan': 0.84,
            'Penyediaan Makanan dan Minuman/Restoran': '-',
            'Perawatan Pribadi dan Jasa Lainnya': 0.43,
        }, 
        'Februari': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Maret': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'April': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Mei': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Juni': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Juli': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Agustus': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'September': {
            'Umum': 0.40,
            'Makanan, Minuman dan Tembakau': 0.40,
            'Pakaian dan Alas Kaki': 0.40,
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': 0.40,
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': 0.40,
            'Kesehatan': 0.40,
            'Transportasi': 0.40,
            'Informasi, Komunikasi dan Jasa Keuangan': 0.40,
            'Rekreasi, Olahraga dan Budaya': 0.40,
            'Pendidikan': 0.40,
            'Penyediaan Makanan dan Minuman/Restoran': 0.40,
            'Perawatan Pribadi dan Jasa Lainnya': 0.40,

        }, 
        'Oktober': {
            'Umum': "-",
            'Makanan, Minuman dan Tembakau': "-",
            'Pakaian dan Alas Kaki': "-",
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': "-",
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': "-",
            'Kesehatan': "-",
            'Transportasi': "-",
            'Informasi, Komunikasi dan Jasa Keuangan': "-",
            'Rekreasi, Olahraga dan Budaya': "-",
            'Pendidikan': "-",
            'Penyediaan Makanan dan Minuman/Restoran': "-",
            'Perawatan Pribadi dan Jasa Lainnya': "-",

        }, 
        'November': {
            'Umum': "-",
            'Makanan, Minuman dan Tembakau': "-",
            'Pakaian dan Alas Kaki': "-",
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': "-",
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': "-",
            'Kesehatan': "-",
            'Transportasi': "-",
            'Informasi, Komunikasi dan Jasa Keuangan': "-",
            'Rekreasi, Olahraga dan Budaya': "-",
            'Pendidikan': "-",
            'Penyediaan Makanan dan Minuman/Restoran': "-",
            'Perawatan Pribadi dan Jasa Lainnya': "-",

        }, 
        'Desember': {
            'Umum': "-",
            'Makanan, Minuman dan Tembakau': "-",
            'Pakaian dan Alas Kaki': "-",
            'Perumahan, Air, Listrik dan Bahan Bakar Rumah Tangga': "-",
            'Perlengkapan, Peralatan dan Pemeliharaan Rutin Rumah Tangga': "-",
            'Kesehatan': "-",
            'Transportasi': "-",
            'Informasi, Komunikasi dan Jasa Keuangan': "-",
            'Rekreasi, Olahraga dan Budaya': "-",
            'Pendidikan': "-",
            'Penyediaan Makanan dan Minuman/Restoran': "-",
            'Perawatan Pribadi dan Jasa Lainnya': "-",
        }}
}
tab1, tab2, tab3= st.tabs(["Konsep & Definisi", "Data", "Visualisasi"])

with tab1:
    st.subheader('Inflasi')
    st.markdown("Kecenderungan naiknya harga barang dan jasa pada umumnya yang berlangsung secara terus menerus. Inflasi dihitung melalui IHK (Indeks Harga Konsumen). Inflasi terdiri dari inflasi month to month (bulanan), year to date (tahun berjalan) dan year on year (tahunan).")

    st.subheader('Indeks Harga Konsumen (IHK)')
    st.markdown('Indeks yang menghitung rata-rata perubahan harga dalam suatu periode, dari suatu kumpulan barang dan jasa yang dikonsumsi oleh penduduk/rumah tangga dalam kurun waktu tertentu.')
    
    st.subheader('Inflasi Year on Year (YoY)')
    st.markdown('Perbandingan IHK bulan n tahun berjalan dibanding IHK bulan yang sama pada tahun sebelumnya')

    st.subheader('Inflasi Month to Month (MtM)')
    st.markdown('Biasa disebut Inflasi Bulanan, dihitung melalui perbandingan IHK bulan berjalan dibanding dengan IHK bulan sebelumnya.')

with tab2:
    option = st.selectbox("Pilih Tahun Data",("2024", "2023", "2022", "2021", "2020"))
    df = pd.DataFrame(inflasi[option])
    st.dataframe(data=df, use_container_width=True)
    st.caption('Sumber: Badan Pusat Statistik (BPS)')

with tab1:
    st.subheader('Visualisasi Belum Tersedia')